export const widgetKinds = [
  "clock",
  "weather",
  "app",
  "iframe",
  "video",
  "notebook",
  "dnsHoleSummary",
  "dnsHoleControls",
  "smartHome-entityState",
  "smartHome-executeAutomation",
  "stockPrice",
  "mediaServer",
  "calendar",
  "downloads",
  "mediaRequests-requestList",
  "mediaRequests-requestStats",
  "mediaTranscoding",
  "minecraftServerStatus",
  "networkControllerSummary",
  "networkControllerStatus",
  "rssFeed",
  "bookmarks",
  "indexerManager",
  "healthMonitoring",
  "releases",
  "mediaReleases",
  "dockerContainers",
  "firewall",
  "notifications",
  "systemResources",
] as const;
export type WidgetKind = (typeof widgetKinds)[number];
