export interface NzbgetHistoryItem {
  NZBID: number;
  Kind: 'NZB' | 'URL' | 'DUP';
  NZBFilename: string;
  Name: string;
  URL: string;
  HistoryTime: number;
  DestDir: string;
  FinalDir: string;
  Category: string;
  FileSizeLo: number;
  FileSizeHi: number;
  FileSizeMB: number;
  FileCount: number;
  RemainingFileCount: number;
  MinPostTime: number;
  MaxPostTime: number;
  TotalArticles: number;
  SuccessArticles: number;
  FailedArticles: number;
  Health: number;
  DownloadedSizeLo: number;
  DownloadedSizeHi: number;
  DownloadedSizeMB: number;
  DownloadTimeSec: number;
  PostTotalTimeSec: number;
  ParTimeSec: number;
  RepairTimeSec: number
  UnpackTimeSec: number;
  MessageCount:number;
  DupeKey: string;
  DupeScore: number;
  DupeMode: 'SCORE' | 'ALL' | 'FORCE';
  Status: string;
  ParStatus: 'NONE' | 'FAILURE' | 'REPAIR_POSSIBLE' | 'SUCCESS' | 'MANUAL';
  ExParStatus: 'RECIPIENT' | 'DONOR';
  UnpackStatus: 'NONE' | 'FAILURE' | 'SPACE' | 'PASSWORD' | 'SUCCESS';
  UrlStatus: 'NONE' | 'SUCCESS' | 'FAILURE' | 'SCAN_SKIPPED' | 'SCAN_FAILURE';
  ScriptStatus: 'NONE' | 'FAILURE' | 'SUCCESS';
  ScriptStatuses: [];
  MoveStatus: 'NONE' | 'SUCCESS' | 'FAILURE';
  DeleteStatus: 'NONE' | 'MANUAL' | 'HEALTH' | 'DUPE' | 'BAD' | 'SCAN' | 'COPY';
  MarkStatus: 'NONE' | 'GOOD' | 'BAD';
  ExtraParBlocks: number;
  Parameters: [];
  ServerStats: [];
}
