version: "2.1"
services:
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
  homarr:
    container_name: homarr
    #image: ghcr.io/ajnart/homarr:latest
    build: # only for dev branch...
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=999 # Must be same as host docker group id
      - DATABASE_URL=file:/app/data/configs/db.sqlite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr_persistence/configs:/app/data/configs
      - ./homarr_persistence/icons:/app/public/icons
    ports:
      - '7575:7575'