name: ✨ Feature Request
description: Request a feature to help improve Homarr!
title: '<title>'
labels: ['✨ Feature']
body:
  - type: textarea
    id: feature
    attributes:
      label: Description 
      description: Describe the feature you would like to see. Tell us how you imagine it and try to provide as much usefull information as possible. **PLEASE** use images or drawings or anything to image your thoughts. Also please do not say "Like X and Y do" as we sometimes don't know what X and Y are.
      placeholder: An outline of the feature you would like to see implemented, include as much detail as possible!
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is the development of this feature?
      options:
        - Low (Nice-to-have)
        - Medium (Would be very useful)
        - High (App breaking feature)
    validations:
      required: true
  - type: checkboxes
    id: idiot-check
    attributes:
      label: Please tick the boxes
      description: Before submitting, please ensure that
      options:
        - label: You've read the [docs](https://github.com/ajnart/homarr#readme)
          required: true
        - label: You've checked for [duplicate issues](https://github.com/ajnart/homarr/issues)
          required: true
