import { Badge, Button, Container, Grid, Group, Stack, Title } from '@mantine/core';
import { useDebouncedValue } from '@mantine/hooks';
import { NextLink } from '@mantine/next';
import { IconMail } from '@tabler/icons';
import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';
import { useTranslation } from 'next-i18next';
import Head from 'next/head';
import { useState } from 'react';
import { openInviteCreateModal } from '../../components/Admin/Invite/InviteCreateModal';
import { useInvitesQuery } from '../../components/Admin/Invite/InviteTable';
import { GenericSearch } from '../../components/Admin/User/UserSearch';
import { UserFilterType, UserList } from '../../components/Admin/User/UserList';
import { useScreenLargerThan } from '../../hooks/useScreenLargerThan';
import { getServerAuthSession } from '../../server/common/get-server-auth-session';
import { getServerSideTranslations } from '../../tools/getServerSideTranslations';

const titleMap: Record<UserFilterType, string> = {
  all: 'All users',
  'user-enabled': 'Enabled users',
  'user-archived': 'Archived users',
  'user-non-admin': 'Non admin users',
  'user-admin': 'Admin users',
};

const useUserFilter = () => {
  const { t } = useTranslation();

  return [
    {
      value: 'all',
      label: 'All users',
    },
    {
      value: 'user-admin',
      label: 'Admin users',
    },
    {
      value: 'user-archived',
      label: 'Archived users',
    },
    {
      value: 'user-enabled',
      label: 'Enabled users',
    },
    {
      value: 'user-non-admin',
      label: 'Non admin users',
    },
  ] as const;
};

const Users: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = () => {
  const [filter, setFilter] = useState<UserFilterType>('all');
  const [search, setSearch] = useState<string>('');
  const [debouncedSearch] = useDebouncedValue(search, 200);
  const largerThanSm = useScreenLargerThan('sm');

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Stack>
          <div>
            <Title>{titleMap[filter]}</Title>
            <Title order={4} weight={400}>
              Manage the users that can access your dashboards.
            </Title>
          </div>

          {largerThanSm ? (
            <Group position="apart" noWrap>
              <GenericSearch
                search={search}
                setSearch={setSearch}
                filters={useUserFilter()}
                applyFilter={(v) => setFilter(v as UserFilterType)}
              />
              <Group noWrap>
                <InvitesButton />
                <Button onClick={openInviteCreateModal}>Invite user</Button>
              </Group>
            </Group>
          ) : (
            <Grid>
              <Grid.Col span={12}>
                <Group noWrap position="apart" grow>
                  <InvitesButton />
                  <Button onClick={openInviteCreateModal}>Invite user</Button>
                </Group>
              </Grid.Col>
              <Grid.Col span={12}>
                <GenericSearch
                  search={search}
                  setSearch={setSearch}
                  filters={useUserFilter()}
                  applyFilter={(v) => setFilter(v as UserFilterType)}
                />
              </Grid.Col>
            </Grid>
          )}
          <UserList search={debouncedSearch} filter={filter} />
        </Stack>
      </Container>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession({
    req: context.req,
    res: context.res,
  });

  const currentUser = await prisma?.user.findFirst({
    where: {
      id: session?.user?.id,
    },
  });

  if (!currentUser?.isAdmin) {
    return {
      notFound: true,
    };
  }

  const translations = await getServerSideTranslations(
    context.req,
    context.res,
    ['common', 'form'],
    context.locale
  );

  return { props: { ...translations } };
};

export default Users;

const InvitesButton = () => {
  const { data: invites } = useInvitesQuery();

  return (
    <Button
      component={NextLink}
      href="/admin/invites"
      variant="default"
      leftIcon={<IconMail size={16} />}
      rightIcon={invites?.length === 0 || !invites ? null : <Badge>{invites.length}</Badge>}
    >
      Invites
    </Button>
  );
};
